version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.akathist.maven.plugins.launch4j:launch4j-maven-plugin
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
